In [1]:
# Import dependencies
import pandas as pd
import numpy as np
import datetime as dt

In [2]:
# Define two rounding functions that will be used to calculate trip time later on
def round_half_up(n, decimals=0):
    multiplier = 10 ** decimals
    return np.floor(n*multiplier + 0.5) / multiplier

def round_half_up_2dec(n, decimals=2):
    multiplier = 10 ** decimals
    return np.floor(n*multiplier + 0.5) / multiplier

In [3]:
# Load all 2021 files
jan_2021 = pd.read_csv("raw_data/JC-202101-citibike-tripdata.csv")
feb_2021 = pd.read_csv("raw_data/JC-202102-citibike-tripdata.csv")
march_2021 = pd.read_csv("raw_data/JC-202103-citibike-tripdata.csv")
april_2021 = pd.read_csv("raw_data/JC-202104-citibike-tripdata.csv")
may_2021 = pd.read_csv("raw_data/JC-202105-citibike-tripdata.csv")
june_2021 = pd.read_csv("raw_data/JC-202106-citibike-tripdata.csv")
july_2021 = pd.read_csv("raw_data/JC-202107-citibike-tripdata.csv")
august_2021 = pd.read_csv("raw_data/JC-202108-citibike-tripdata.csv")
september_2021 = pd.read_csv("raw_data/JC-202109-citibike-tripdata.csv")
october_2021 = pd.read_csv("raw_data/JC-202110-citibike-tripdata.csv")
november_2021 = pd.read_csv("raw_data/JC-202111-citibike-tripdata.csv")
december_2021 = pd.read_csv("raw_data/JC-202112-citibike-tripdata.csv")

In [4]:
# Rename columns for January dataframe
jan_2021.rename(columns={"tripduration":"Trip Duration (sec)",
                         "starttime":"Start Time",
                         "stoptime":"Stop Time",
                         "start station name":"Start Station Name",
                         "start station latitude":"Start Lat",
                         "start station longitude":"Start Lon",
                         "end station name":"End Station Name",
                         "end station latitude":"End Lat",
                         "end station longitude":"End Lon",
                         "usertype":"User Type"}, inplace=True)

jan_2021

,Trip Duration (sec),Start Time,Stop Time,start station id,Start Station Name,Start Lat,Start Lon,end station id,End Station Name,End Lat,End Lon,bikeid,User Type,birth year,gender
0,266,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273,Manila & 1st,40.721651,-74.042884,3209,Brunswick St,40.724176,-74.050656,42494,Subscriber,1988,1
1,1543,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,45343,Customer,1996,2
2,1461,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681,Grand St,40.715178,-74.037683,3213,Van Vorst Park,40.718489,-74.047727,31794,Customer,1995,1
3,793,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185,City Hall,40.717733,-74.043845,3199,Newport Pkwy,40.728745,-74.032108,42316,Customer,1969,0
4,596,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639,Harborside,40.719252,-74.034234,3209,Brunswick St,40.724176,-74.050656,32575,Customer,1969,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11619,2476,2021-01-31 20:16:05.4700,2021-01-31 20:57:22.0110,3187,Warren St,40.721124,-74.038051,3483,Montgomery St,40.719420,-74.050990,44852,Subscriber,1958,1
11620,147,2021-01-31 21:05:05.2090,2021-01-31 21:07:32.8660,3186,Grove St PATH,40.719586,-74.043117,3187,Warren St,40.721124,-74.038051,46538,Subscriber,1972,1
11621,660,2021-01-31 21:06:23.5880,2021-01-31 21:17:23.8420,3211,Newark Ave,40.721525,-74.046305,3276,Marin Light Rail,40.714584,-74.042817,44398,Subscriber,1987,2
11622,384,2021-01-31 21:16:37.8220,2021-01-31 21:23:02.1240,3205,JC Medical Center,40.716540,-74.049638,3268,Lafayette Park,40.713464,-74.062859,41400,Subscriber,1989,1
11623,356,2021-01-31 23:24:50.8810,2021-01-31 23:30:47.3030,3639,Harborside,40.719252,-74.034234,3186,Grove St PATH,40.719586,-74.043117,43766,Subscriber,1994,1

In [5]:
# February onwards have different column names compared to January, 
# so we have to rename them to match the format from previous years.
print(jan_2021.columns.tolist())
print(feb_2021.columns.tolist())

['Trip Duration (sec)', 'Start Time', 'Stop Time', 'start station id', 'Start Station Name', 'Start Lat', 'Start Lon', 'end station id', 'End Station Name', 'End Lat', 'End Lon', 'bikeid', 'User Type', 'birth year', 'gender']
['ride_id', 'rideable_type', 'started_at', 'ended_at', 'start_station_name', 'start_station_id', 'end_station_name', 'end_station_id', 'start_lat', 'start_lng', 'end_lat', 'end_lng', 'member_casual']

In [6]:
# Rename columns for other dataframes by iterating through them
dfs = [feb_2021, march_2021, april_2021, may_2021, june_2021, 
       july_2021, august_2021, september_2021, october_2021, 
       november_2021, december_2021]
col_names = {
    "started_at": "Start Time",
    "ended_at": "Stop Time",
    "start_station_name": "Start Station Name",
    "start_lat": "Start Lat",
    "start_lng": "Start Lon",
    "end_station_name":"End Station Name",
    "end_lat":"End Lat",
    "end_lng":"End Lon",
    "member_casual":"User Type"
}
for df in dfs:
    for col in col_names:
        if col in df.columns:
            df.rename(columns={col: col_names.get(col)}, inplace=True)
    print(df.columns.tolist())

['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']
['ride_id', 'rideable_type', 'Start Time', 'Stop Time', 'Start Station Name', 'start_station_id', 'End Station Name', 'end_station_id', 'Start Lat', 'Start Lon', 'End Lat', 'End Lon', 'User Type']

In [7]:
# Combine DataFrame objects with overlapping columns and 
# return only those that are shared by passing inner to the join keyword argument.
all_2021 = pd.concat([jan_2021, 
                  feb_2021, 
                  march_2021, 
                  april_2021, 
                  may_2021, 
                  june_2021, 
                  july_2021, 
                  august_2021, 
                  september_2021,
                  october_2021,
                  november_2021,
                  december_2021], ignore_index=True)
all_2021

,Trip Duration (sec),Start Time,Stop Time,start station id,Start Station Name,Start Lat,Start Lon,end station id,End Station Name,End Lat,End Lon,bikeid,User Type,birth year,gender,ride_id,rideable_type,start_station_id,end_station_id
0,266.0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,3273.0,Manila & 1st,40.721651,-74.042884,3209.0,Brunswick St,40.724176,-74.050656,42494.0,Subscriber,1988.0,1.0,NaN,NaN,NaN,NaN
1,1543.0,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,-74.047727,45343.0,Customer,1996.0,2.0,NaN,NaN,NaN,NaN
2,1461.0,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,3681.0,Grand St,40.715178,-74.037683,3213.0,Van Vorst Park,40.718489,-74.047727,31794.0,Customer,1995.0,1.0,NaN,NaN,NaN,NaN
3,793.0,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,3185.0,City Hall,40.717733,-74.043845,3199.0,Newport Pkwy,40.728745,-74.032108,42316.0,Customer,1969.0,0.0,NaN,NaN,NaN,NaN
4,596.0,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,3639.0,Harborside,40.719252,-74.034234,3209.0,Brunswick St,40.724176,-74.050656,32575.0,Customer,1969.0,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
644438,NaN,2021-12-16 17:17:46,2021-12-16 17:22:53,NaN,Grove St PATH,40.719586,-74.043117,NaN,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,13FE513C650901A3,classic_bike,JC005,JC009
644439,NaN,2021-12-07 17:10:29,2021-12-07 17:15:02,NaN,Grove St PATH,40.719586,-74.043117,NaN,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,CA29051F38E67D30,classic_bike,JC005,JC009
644440,NaN,2021-12-18 09:50:14,2021-12-18 09:55:55,NaN,Grove St PATH,40.719586,-74.043117,NaN,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,A719DEA143005404,classic_bike,JC005,JC009
644441,NaN,2021-12-10 21:43:32,2021-12-10 21:49:04,NaN,Grove St PATH,40.719586,-74.043117,NaN,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,D39126975208B59D,classic_bike,JC005,JC009
644442,NaN,2021-12-08 11:09:56,2021-12-08 11:14:58,NaN,Hilltop,40.731169,-74.057574,NaN,Hamilton Park,40.727596,-74.044247,NaN,member,NaN,NaN,1BB5CF43B5DF7E05,classic_bike,JC019,JC009

In [8]:
# Remove unecessary columns (want to be able to make comparisons across multiple years of data and rider demographics not
# present in later years.)

all_2021 = all_2021[["Start Time",
                     "Stop Time",
                     "Start Station Name",
                     "Start Lat",
                     "Start Lon",
                     "End Station Name",
                     "End Lat",
                     "End Lon",
                     "User Type",
                     "Trip Duration (sec)"]]

all_2021

,Start Time,Stop Time,Start Station Name,Start Lat,Start Lon,End Station Name,End Lat,End Lon,User Type,Trip Duration (sec)
0,2021-01-01 00:03:35.5100,2021-01-01 00:08:01.7770,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,Subscriber,266.0
1,2021-01-01 00:23:32.9250,2021-01-01 00:49:16.0830,Grand St,40.715178,-74.037683,Van Vorst Park,40.718489,-74.047727,Customer,1543.0
2,2021-01-01 00:23:50.7940,2021-01-01 00:48:12.5660,Grand St,40.715178,-74.037683,Van Vorst Park,40.718489,-74.047727,Customer,1461.0
3,2021-01-01 00:31:09.0770,2021-01-01 00:44:22.9430,City Hall,40.717733,-74.043845,Newport Pkwy,40.728745,-74.032108,Customer,793.0
4,2021-01-01 00:35:52.1900,2021-01-01 00:45:48.7740,Harborside,40.719252,-74.034234,Brunswick St,40.724176,-74.050656,Customer,596.0
...,...,...,...,...,...,...,...,...,...,...
644438,2021-12-16 17:17:46,2021-12-16 17:22:53,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,NaN
644439,2021-12-07 17:10:29,2021-12-07 17:15:02,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,NaN
644440,2021-12-18 09:50:14,2021-12-18 09:55:55,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,NaN
644441,2021-12-10 21:43:32,2021-12-10 21:49:04,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,NaN
644442,2021-12-08 11:09:56,2021-12-08 11:14:58,Hilltop,40.731169,-74.057574,Hamilton Park,40.727596,-74.044247,member,NaN

In [9]:
# Convert start and stop times to datetime (y-m-d h:s:ms)
all_2021['Start Time'] = pd.to_datetime(all_2021['Start Time'])
all_2021["Stop Time"] = pd.to_datetime(all_2021['Stop Time'])

all_2021.dtypes

C:\Users\sarah\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sarah\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

Start Time             datetime64[ns]
Stop Time              datetime64[ns]
Start Station Name             object
Start Lat                     float64
Start Lon                     float64
End Station Name               object
End Lat                       float64
End Lon                       float64
User Type                      object
Trip Duration (sec)           float64
dtype: object

In [10]:
# Create two new columns, one for trip duration in mins and one in hrs (better to do this now than in Tableau)
all_2021['Trip Duration (sec)'] = round_half_up((all_2021["Stop Time"]-all_2021["Start Time"])/pd.Timedelta(seconds=1))
all_2021['Trip Duration (min)'] = round_half_up_2dec((all_2021["Stop Time"]-all_2021['Start Time'])/pd.Timedelta(minutes=1))
all_2021['Trip Duration (hrs)'] = round_half_up_2dec((all_2021["Stop Time"]-all_2021['Start Time'])/pd.Timedelta(hours=1))

all_2021

C:\Users\sarah\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

C:\Users\sarah\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\sarah\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,Start Time,Stop Time,Start Station Name,Start Lat,Start Lon,End Station Name,End Lat,End Lon,User Type,Trip Duration (sec),Trip Duration (min),Trip Duration (hrs)
0,2021-01-01 00:03:35.510,2021-01-01 00:08:01.777,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,Subscriber,266.0,4.44,0.07
1,2021-01-01 00:23:32.925,2021-01-01 00:49:16.083,Grand St,40.715178,-74.037683,Van Vorst Park,40.718489,-74.047727,Customer,1543.0,25.72,0.43
2,2021-01-01 00:23:50.794,2021-01-01 00:48:12.566,Grand St,40.715178,-74.037683,Van Vorst Park,40.718489,-74.047727,Customer,1462.0,24.36,0.41
3,2021-01-01 00:31:09.077,2021-01-01 00:44:22.943,City Hall,40.717733,-74.043845,Newport Pkwy,40.728745,-74.032108,Customer,794.0,13.23,0.22
4,2021-01-01 00:35:52.190,2021-01-01 00:45:48.774,Harborside,40.719252,-74.034234,Brunswick St,40.724176,-74.050656,Customer,597.0,9.94,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...
644438,2021-12-16 17:17:46.000,2021-12-16 17:22:53.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,307.0,5.12,0.09
644439,2021-12-07 17:10:29.000,2021-12-07 17:15:02.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,273.0,4.55,0.08
644440,2021-12-18 09:50:14.000,2021-12-18 09:55:55.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,341.0,5.68,0.09
644441,2021-12-10 21:43:32.000,2021-12-10 21:49:04.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,332.0,5.53,0.09
644442,2021-12-08 11:09:56.000,2021-12-08 11:14:58.000,Hilltop,40.731169,-74.057574,Hamilton Park,40.727596,-74.044247,member,302.0,5.03,0.08

In [11]:
# Remove any NaN valuesand reset the index for a cleaner dataset
all_2021.dropna(inplace=True)
all_2021 = all_2021.reset_index(drop=True)

all_2021

C:\Users\sarah\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Start Time,Stop Time,Start Station Name,Start Lat,Start Lon,End Station Name,End Lat,End Lon,User Type,Trip Duration (sec),Trip Duration (min),Trip Duration (hrs)
0,2021-01-01 00:03:35.510,2021-01-01 00:08:01.777,Manila & 1st,40.721651,-74.042884,Brunswick St,40.724176,-74.050656,Subscriber,266.0,4.44,0.07
1,2021-01-01 00:23:32.925,2021-01-01 00:49:16.083,Grand St,40.715178,-74.037683,Van Vorst Park,40.718489,-74.047727,Customer,1543.0,25.72,0.43
2,2021-01-01 00:23:50.794,2021-01-01 00:48:12.566,Grand St,40.715178,-74.037683,Van Vorst Park,40.718489,-74.047727,Customer,1462.0,24.36,0.41
3,2021-01-01 00:31:09.077,2021-01-01 00:44:22.943,City Hall,40.717733,-74.043845,Newport Pkwy,40.728745,-74.032108,Customer,794.0,13.23,0.22
4,2021-01-01 00:35:52.190,2021-01-01 00:45:48.774,Harborside,40.719252,-74.034234,Brunswick St,40.724176,-74.050656,Customer,597.0,9.94,0.17
...,...,...,...,...,...,...,...,...,...,...,...,...
640938,2021-12-16 17:17:46.000,2021-12-16 17:22:53.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,307.0,5.12,0.09
640939,2021-12-07 17:10:29.000,2021-12-07 17:15:02.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,273.0,4.55,0.08
640940,2021-12-18 09:50:14.000,2021-12-18 09:55:55.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,341.0,5.68,0.09
640941,2021-12-10 21:43:32.000,2021-12-10 21:49:04.000,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,member,332.0,5.53,0.09
640942,2021-12-08 11:09:56.000,2021-12-08 11:14:58.000,Hilltop,40.731169,-74.057574,Hamilton Park,40.727596,-74.044247,member,302.0,5.03,0.08

In [12]:
# To match the User Types from previous years, we will be renaming "member" to "Subscriber" and "casual" to "Customer"
all_2021["User Type"]=all_2021["User Type"].replace(["member","casual"],["Subscriber","Customer"])

all_2021["User Type"].value_counts()

Subscriber    382333
Customer      258610
Name: User Type, dtype: int64

In [13]:
# Export to .csv
all_2021.index.rename("Ride ID", inplace=True)

all_2021.to_csv("cleaned_data/rides_2021.csv")