In [7]:
# Import dependencies
import pandas as pd

In [8]:
# Read in all three dataframes
df_2019 = pd.read_csv("cleaned_data/rides_2019.csv")
df_2020 = pd.read_csv("cleaned_data/rides_2020.csv")
df_2021 = pd.read_csv("cleaned_data/rides_2021.csv")

In [9]:
# list all column names to ensure they are the same
dfs=[df_2019, df_2020, df_2021]

for df in dfs:
    print(df.columns.tolist())

['Ride ID', 'Start Time', 'Stop Time', 'Start Station Name', 'Start Lat', 'Start Lon', 'End Station Name', 'End Lat', 'End Lon', 'User Type', 'Trip Duration (sec)', 'Trip Duration (min)', 'Trip Duration (hrs)']
['Ride ID', 'Start Time', 'Stop Time', 'Start Station Name', 'Start Lat', 'Start Lon', 'End Station Name', 'End Lat', 'End Lon', 'User Type', 'Trip Duration (sec)', 'Trip Duration (min)', 'Trip Duration (hrs)']
['Ride ID', 'Start Time', 'Stop Time', 'Start Station Name', 'Start Lat', 'Start Lon', 'End Station Name', 'End Lat', 'End Lon', 'User Type', 'Trip Duration (sec)', 'Trip Duration (min)', 'Trip Duration (hrs)']

In [10]:
# Merge all dataframes together
all_data = pd.concat([df_2019, df_2020, df_2021])

all_data

,Ride ID,Start Time,Stop Time,Start Station Name,Start Lat,Start Lon,End Station Name,End Lat,End Lon,User Type,Trip Duration (sec),Trip Duration (min),Trip Duration (hrs)
0,0,2019-01-01 03:09:09.711,2019-01-01 03:12:30.879,Exchange Place,40.716247,-74.033459,Essex Light Rail,40.712774,-74.036486,Subscriber,201.0,3.35,0.06
1,1,2019-01-01 05:18:00.106,2019-01-01 05:26:25.905,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Subscriber,505.0,8.43,0.14
2,2,2019-01-01 10:36:33.340,2019-01-01 10:49:10.260,Exchange Place,40.716247,-74.033459,Liberty Light Rail,40.711242,-74.055701,Subscriber,756.0,12.62,0.21
3,3,2019-01-01 12:43:38.643,2019-01-01 13:09:54.528,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Customer,1575.0,26.26,0.44
4,4,2019-01-01 12:43:39.601,2019-01-01 13:09:46.510,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Customer,1566.0,26.12,0.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
640938,640938,2021-12-16 17:17:46,2021-12-16 17:22:53,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,307.0,5.12,0.09
640939,640939,2021-12-07 17:10:29,2021-12-07 17:15:02,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,273.0,4.55,0.08
640940,640940,2021-12-18 09:50:14,2021-12-18 09:55:55,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,341.0,5.68,0.09
640941,640941,2021-12-10 21:43:32,2021-12-10 21:49:04,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,332.0,5.53,0.09
640942,640942,2021-12-08 11:09:56,2021-12-08 11:14:58,Hilltop,40.731169,-74.057574,Hamilton Park,40.727596,-74.044247,Subscriber,302.0,5.03,0.08

In [11]:
# Remove any rows where trip duration is less than 1 minute
all_data = all_data.loc[all_data["Trip Duration (min)"]>=1,:]
all_data

,Ride ID,Start Time,Stop Time,Start Station Name,Start Lat,Start Lon,End Station Name,End Lat,End Lon,User Type,Trip Duration (sec),Trip Duration (min),Trip Duration (hrs)
0,0,2019-01-01 03:09:09.711,2019-01-01 03:12:30.879,Exchange Place,40.716247,-74.033459,Essex Light Rail,40.712774,-74.036486,Subscriber,201.0,3.35,0.06
1,1,2019-01-01 05:18:00.106,2019-01-01 05:26:25.905,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Subscriber,505.0,8.43,0.14
2,2,2019-01-01 10:36:33.340,2019-01-01 10:49:10.260,Exchange Place,40.716247,-74.033459,Liberty Light Rail,40.711242,-74.055701,Subscriber,756.0,12.62,0.21
3,3,2019-01-01 12:43:38.643,2019-01-01 13:09:54.528,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Customer,1575.0,26.26,0.44
4,4,2019-01-01 12:43:39.601,2019-01-01 13:09:46.510,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Customer,1566.0,26.12,0.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
640938,640938,2021-12-16 17:17:46,2021-12-16 17:22:53,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,307.0,5.12,0.09
640939,640939,2021-12-07 17:10:29,2021-12-07 17:15:02,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,273.0,4.55,0.08
640940,640940,2021-12-18 09:50:14,2021-12-18 09:55:55,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,341.0,5.68,0.09
640941,640941,2021-12-10 21:43:32,2021-12-10 21:49:04,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,332.0,5.53,0.09
640942,640942,2021-12-08 11:09:56,2021-12-08 11:14:58,Hilltop,40.731169,-74.057574,Hamilton Park,40.727596,-74.044247,Subscriber,302.0,5.03,0.08

In [13]:
# Remove any rows where lat or lon is 0
all_data = all_data.loc[(all_data["End Lat"]!=0) & 
                        (all_data["Start Lat"]!=0) & 
                        (all_data["End Lon"]!=0) & 
                        (all_data["Start Lon"]!=0),:]

all_data

,Ride ID,Start Time,Stop Time,Start Station Name,Start Lat,Start Lon,End Station Name,End Lat,End Lon,User Type,Trip Duration (sec),Trip Duration (min),Trip Duration (hrs)
0,0,2019-01-01 03:09:09.711,2019-01-01 03:12:30.879,Exchange Place,40.716247,-74.033459,Essex Light Rail,40.712774,-74.036486,Subscriber,201.0,3.35,0.06
1,1,2019-01-01 05:18:00.106,2019-01-01 05:26:25.905,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Subscriber,505.0,8.43,0.14
2,2,2019-01-01 10:36:33.340,2019-01-01 10:49:10.260,Exchange Place,40.716247,-74.033459,Liberty Light Rail,40.711242,-74.055701,Subscriber,756.0,12.62,0.21
3,3,2019-01-01 12:43:38.643,2019-01-01 13:09:54.528,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Customer,1575.0,26.26,0.44
4,4,2019-01-01 12:43:39.601,2019-01-01 13:09:46.510,Exchange Place,40.716247,-74.033459,Washington St,40.724294,-74.035483,Customer,1566.0,26.12,0.44
...,...,...,...,...,...,...,...,...,...,...,...,...,...
640938,640938,2021-12-16 17:17:46,2021-12-16 17:22:53,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,307.0,5.12,0.09
640939,640939,2021-12-07 17:10:29,2021-12-07 17:15:02,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,273.0,4.55,0.08
640940,640940,2021-12-18 09:50:14,2021-12-18 09:55:55,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,341.0,5.68,0.09
640941,640941,2021-12-10 21:43:32,2021-12-10 21:49:04,Grove St PATH,40.719586,-74.043117,Hamilton Park,40.727596,-74.044247,Subscriber,332.0,5.53,0.09
640942,640942,2021-12-08 11:09:56,2021-12-08 11:14:58,Hilltop,40.731169,-74.057574,Hamilton Park,40.727596,-74.044247,Subscriber,302.0,5.03,0.08

In [14]:
# Export to CSV
all_data.to_csv("cleaned_data/all_data.csv", index=False)